AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Instance > App-Instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Resource Identity"
        Parameters:
          - StackExportPrefix
          - pEnvironment
          - pResourceName
      - Label:
          default: "InfraStack Resource"
        Parameters:
          - VPC
          - Subnet1
      - Label:
          default: "Instance Configuration"
        Parameters:
          #- pKeyPair
          - pTargetPort

Parameters:
  StackExportPrefix:
    Type: "String"
    Default: "project-dev-t2"
  pEnvironment:
    Type: "String"
    Default: "dev"
  pResourceName:
    Type: String
    Default: "AppInstance"
    AllowedPattern: "[A-Za-z0-9]*"
    MaxLength: 12

  pTargetPort:
    Type: Number
    Default: 80




  VPC:
    Type: String
    Default: "VPC"
  Subnet1:
    Type: String
    Default: "PrivateSubnet1"
  Subnet2:
    Type: String
    Default: "PrivateSubnet2"
  SGInstance:
    Type: String
    Default: "AppServerSG"

Mappings:
  InstanceMap:
    InstanceType:
      dev: "t2.micro"
      test: "t2.micro"
      stage: "t2.micro"
      prod: "t2.micro"
  ImageMap:
    us-east-1:
      dev: "ami-051f8a213df8bc089"


Resources:
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:

        - Fn::ImportValue: !Sub "${StackExportPrefix}-IAMRole-WebServerRole"
  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: my-keypair
  Instance1:
    Type: AWS::EC2::Instance
    DependsOn:
      - IamInstanceProfile
    Properties:
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !FindInMap
        - ImageMap
        - !Ref "AWS::Region"
        - !Ref pEnvironment
      InstanceType: !FindInMap
        - InstanceMap
        - "InstanceType"
        - !Ref pEnvironment
      KeyName: !Ref MyKeyPair
      NetworkInterfaces:
        - DeleteOnTermination: true
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue: !Sub "${StackExportPrefix}-${Subnet1}"
          GroupSet:
            - Fn::ImportValue: !Sub "${StackExportPrefix}-SG-${SGInstance}"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            yum update -y
            sudo yum install python3 -y
            sudo yum install python3-pip -y

      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: StackExportPrefix
          Value: !Ref StackExportPrefix
        - Key: pEnvironment
          Value: !Ref pEnvironment
        - Key: Name
          Value: !Sub "${StackExportPrefix}-${pResourceName}-EC2"

 ########################################################################################################################################


  Instance2:
    Type: AWS::EC2::Instance
    DependsOn:
      - IamInstanceProfile
    Properties:
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !FindInMap
        - ImageMap
        - !Ref "AWS::Region"
        - !Ref pEnvironment
      InstanceType: !FindInMap
        - InstanceMap
        - "InstanceType"
        - !Ref pEnvironment
      KeyName: !Ref MyKeyPair
      NetworkInterfaces:
        - DeleteOnTermination: true
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue: !Sub "${StackExportPrefix}-${Subnet2}"
          GroupSet:
            - Fn::ImportValue: !Sub "${StackExportPrefix}-SG-${SGInstance}"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            yum update -y
            sudo yum install python3 -y
            sudo yum install python3-pip -y

      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: StackExportPrefix
          Value: !Ref StackExportPrefix
        - Key: pEnvironment
          Value: !Ref pEnvironment
        - Key: Name
          Value: !Sub "${StackExportPrefix}-${pResourceName}-EC2"


############################################################################################

Outputs:
  Instance1:
    Description: A reference to the Instance
    Value: !Ref Instance1
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-AppInstance1"
  Instance2:
    Description: A reference to the Instance
    Value: !Ref Instance2
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-AppInstance2"

  Instance1PrivateIp:
    Description: A reference to the Instance PrivateIp
    Value: !GetAtt Instance1.PrivateIp
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-Instance1PrivateIp"

  Instance2PrivateIp:
    Description: A reference to the Instance PrivateIp
    Value: !GetAtt Instance2.PrivateIp
    Export:
      Name: !Sub "${StackExportPrefix}-${pResourceName}-Instance2PrivateIp"
